<Project>
    <PropertyGroup>
        <!--        <Contributors>fsdg</Contributors>-->
        <ModType>code</ModType>
        <Side>universal</Side>
        <RequiredOnClient>true</RequiredOnClient>
        <RequiredOnServer>true</RequiredOnServer>
    </PropertyGroup>
    <ItemGroup>
        <!-- Fetch controls whether to automatically download the mod from moddb as a dependency -->
        <Dependency Include="game" Version="*" Fetch="false"/>
        <Dependency Include="vsimgui" Version="1.2.2" />
        <Dependency Include="insanitylib" Version="2.0.1" Fetch="false"/>
        <Dependency Include="jsonpatcheslib" Version="1.4.1" />
        <Dependency Include="vintageengineering" Version="0.5.4"/>
        <Dependency Include="attributerenderinglibrary" Version="3.1.0" Fetch="false"/>
    </ItemGroup>
</Project>
