<Project Sdk="Microsoft.NET.Sdk">
  <!-- Mod info -->
  <PropertyGroup>
    <Description></Description>
    <Authors>OmegaRogue,TheLegend666,RolfSteiner</Authors>

    <PackageId>thaumaturgy</PackageId>
    <Version>0.1.0</Version>
    <PackageProjectUrl>https://github.com/OmegaVoid/OmegaMods</PackageProjectUrl>
    <RepositoryUrl>https://github.com/OmegaVoid/OmegaMods</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Title>Thaumaturgy</Title>
  </PropertyGroup>

  <!-- Project settings -->
  <PropertyGroup>
    <OutputDir>bin\$(Configuration)</OutputDir>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Releases\" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Path to your ModInfo file -->
    <ModInfoFile>$(OutputPath)/modinfo.json</ModInfoFile>

    <!-- Enables the generation of the xml documentation file (used by some InsanityLib features) -->
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <ModID>$(PackageId)</ModID>
    <HasInsanityLibDependency>true<!--TODO check properly--></HasInsanityLibDependency>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="ModID" />
    <CompilerVisibleProperty Include="HasInsanityLibDependency" />
  </ItemGroup>

  <!-- References to libraries that are being used in project -->
  <ItemGroup>
    <PackageReference Include="TheInsanityGod.VintageStory.InsanityLib" Version="2.*" PrivateAssets="All" />
    <PackageReference Include="JsonPeek" Version="1.2.0" />

    <PackageReference Include="OmegaVoid.VintageStory.Sdk.Tasks" Version="0.1.5" />
  </ItemGroup>

</Project>