<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="VintagestoryAPI">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/VintagestoryAPI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="VSSurvivalMod">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Mods/VSSurvivalMod.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VSEssentials">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Mods/VSEssentials.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VSCreativeMod">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Mods/VSCreativeMod.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Lib/Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Lib/0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VintagestoryLib">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/VintagestoryLib.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="protobuf-net">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Lib/protobuf-net.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="cairo-sharp">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Lib/cairo-sharp.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.Data.Sqlite">
            <HintPath>/home/omegarogue/.config/VSLGameVersions/1.22.0-rc.9/Lib/Microsoft.Data.Sqlite.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="modinfo.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Include="modicon.png" Condition="Exists('modicon.png')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
